apiVersion: v1
kind: Service
metadata:
  name: todo-nginx
  labels:
    app: todo-nginx
spec:
  type: NodePort
  selector:
    app: todo-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30080
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
